import React, { useEffect, useMemo, useState } from 'react';
import { Archive, BookOpen, CheckCircle2, Edit3, Image as ImageIcon, Plus, RefreshCw, Save, Search, Upload, X } from 'lucide-react';
import { useApp } from '../contexts/AppContext';
import { archiveExercise, canManageExerciseLibrary, createExercise, updateExercise, uploadExerciseMedia } from '../lib/training';

const groups = ['Peito','Costas','Ombros','Bíceps','Tríceps','Pernas','Quadríceps','Posteriores','Glúteos','Gémeos','Core','Corpo inteiro','Funcional','Cross Training','Mobilidade','Alongamentos','Cardio'];
const categories = ['Força','Hipertrofia','Funcional','Cross Training','Mobilidade','Alongamento','Cardio','Pliometria','Estabilidade','Condicionamento','Prevenção'];
const difficulties = ['Iniciante','Intermédio','Avançado'];

function ExerciseMedia({ exercise }) {
  if (!exercise?.mediaUrl) return <div className="exerciseMedia"><BookOpen size={28}/><span>Adicionar demonstração</span></div>;
  if (exercise.mediaKind === 'video') return <div className="exerciseMedia real"><video src={exercise.mediaUrl} muted playsInline preload="metadata"/></div>;
  return <div className="exerciseMedia real"><img src={exercise.mediaUrl} alt={exercise.name} loading="lazy"/></div>;
}

function emptyExercise() { return { id:'', name:'', description:'', group:'Pernas', secondaryMuscles:[], equipment:'', category:'Força', difficulty:'Intermédio', instructions:'', mediaPath:'', mediaKind:'', externalMediaUrl:'', active:true }; }

function ExerciseForm({ initial, onCancel, onSaved }) {
  const { refreshTraining } = useApp();
  const [draft,setDraft] = useState({...initial});
  const [file,setFile] = useState(null);
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState('');
  function patch(key,value){setDraft(current=>({...current,[key]:value}))}
  async function submit(event){event.preventDefault();setBusy(true);setError('');try{let mediaPath=draft.mediaPath;let mediaKind=draft.mediaKind;if(file){const uploaded=await uploadExerciseMedia(file);mediaPath=uploaded.path;mediaKind=uploaded.kind;}const payload={...draft,mediaPath,mediaKind};const saved=draft.id?await updateExercise(draft.id,payload):await createExercise(payload);await refreshTraining();onSaved(saved.id);}catch(err){setError(err.message||'Não foi possível guardar o exercício.')}finally{setBusy(false)}}
  return <div className="exerciseFormPage"><button className="backButton" onClick={onCancel}>← Voltar à biblioteca</button><div className="heading"><div><span className="eyebrow">BIBLIOTECA DE EXERCÍCIOS</span><h1>{draft.id?'Editar exercício':'Novo exercício'}</h1><p>A demonstração pode ser imagem otimizada, GIF, vídeo curto ou URL externa.</p></div></div>{error&&<div className="errorBanner">{error}</div>}<form onSubmit={submit} className="card pad exerciseEditorForm"><div className="formGrid"><label className="wide">Nome*<input required value={draft.name} onChange={event=>patch('name',event.target.value)} placeholder="Ex.: Agachamento Goblet"/></label><label>Grupo muscular*<select value={draft.group} onChange={event=>patch('group',event.target.value)}>{groups.map(item=><option key={item}>{item}</option>)}</select></label><label>Categoria<select value={draft.category} onChange={event=>patch('category',event.target.value)}>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Equipamento<input value={draft.equipment} onChange={event=>patch('equipment',event.target.value)} placeholder="Barra, halteres, TRX…"/></label><label>Dificuldade<select value={draft.difficulty} onChange={event=>patch('difficulty',event.target.value)}>{difficulties.map(item=><option key={item}>{item}</option>)}</select></label><label className="wide">Descrição<textarea value={draft.description} onChange={event=>patch('description',event.target.value)} placeholder="Resumo simples do exercício."/></label><label className="wide">Instruções técnicas<textarea value={draft.instructions} onChange={event=>patch('instructions',event.target.value)} placeholder="Pontos de execução, erros a evitar, adaptações…"/></label><div className="wide exerciseMediaUpload"><div><ImageIcon/><b>Demonstração</b><small>JPG/PNG/WebP são convertidos automaticamente para WebP. GIF/MP4/WebM até 15 MB.</small></div><label className="secondary"><Upload size={16}/>Escolher ficheiro<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" onChange={event=>setFile(event.target.files?.[0]||null)} hidden/></label>{file&&<span>{file.name}</span>}</div><label className="wide">Ou URL externa<input value={draft.externalMediaUrl} onChange={event=>patch('externalMediaUrl',event.target.value)} placeholder="https://…"/></label><label className="exerciseActiveToggle"><input type="checkbox" checked={draft.active} onChange={event=>patch('active',event.target.checked)}/><span>Exercício ativo e disponível para novos planos</span></label></div><div className="modalActions"><button type="button" className="secondary" onClick={onCancel}>Cancelar</button><button className="primary" disabled={busy}><Save size={17}/>{busy?'A guardar…':'Guardar exercício'}</button></div></form></div>;
}

export default function ExerciseLibraryModule(){
  const {data,currentUser,refreshTraining,trainingLoading,trainingError}=useApp();
  const [canManage,setCanManage]=useState(currentUser.role==='admin');
  const [q,setQ]=useState('');const [group,setGroup]=useState('Todos');const [status,setStatus]=useState('active');const [editing,setEditing]=useState(null);const [notice,setNotice]=useState('');const [error,setError]=useState('');
  useEffect(()=>{if(currentUser.role!=='aluno')canManageExerciseLibrary().then(setCanManage)},[currentUser.id,currentUser.role]);
  const availableGroups=useMemo(()=>['Todos',...new Set(data.exercises.map(item=>item.group).filter(Boolean))],[data.exercises]);
  const list=useMemo(()=>data.exercises.filter(exercise=>{const query=q.trim().toLowerCase();if(status==='active'&&!exercise.active)return false;if(status==='inactive'&&exercise.active)return false;if(group!=='Todos'&&exercise.group!==group)return false;return !query||exercise.name.toLowerCase().includes(query)||exercise.equipment.toLowerCase().includes(query)||exercise.category.toLowerCase().includes(query)}),[data.exercises,q,group,status]);
  if(editing)return <ExerciseForm initial={editing} onCancel={()=>setEditing(null)} onSaved={()=>{setEditing(null);setNotice('Exercício guardado.')}}/>;
  async function toggle(exercise){setError('');try{await archiveExercise(exercise.id,!exercise.active);await refreshTraining();setNotice(exercise.active?'Exercício arquivado.':'Exercício reativado.')}catch(err){setError(err.message)}}
  return <div className="exerciseLibraryPage"><div className="heading"><div><h1>Biblioteca de exercícios</h1><p>{data.exercises.filter(item=>item.active).length} exercícios ativos. Imagens otimizadas e suporte a GIF/vídeo.</p></div>{canManage&&<button className="primary" onClick={()=>setEditing(emptyExercise())}><Plus size={17}/>Novo exercício</button>}</div>{(trainingError||error)&&<div className="errorBanner">{trainingError||error}</div>}{notice&&<div className="successBanner"><CheckCircle2 size={17}/>{notice}</div>}<div className="filters exerciseLibraryFilters"><div className="search"><Search size={18}/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Pesquisar exercício…"/></div><select value={group} onChange={event=>setGroup(event.target.value)}>{availableGroups.map(item=><option key={item}>{item}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)}><option value="active">Ativos</option><option value="inactive">Arquivados</option><option value="all">Todos</option></select></div>{trainingLoading?<div className="notice">A carregar biblioteca…</div>:<div className="grid three exerciseLibraryGrid">{list.map(exercise=><article className="card exerciseCard realExerciseCard" key={exercise.id}><ExerciseMedia exercise={exercise}/><div className="pad"><div className="exerciseCardBadges"><span className="badge yellow">{exercise.group}</span>{exercise.category&&<span className="badge gray">{exercise.category}</span>}{!exercise.active&&<span className="badge gray">Arquivado</span>}</div><h3>{exercise.name}</h3><small>{exercise.equipment||'Sem equipamento'}{exercise.difficulty?` · ${exercise.difficulty}`:''}</small><p>{exercise.description||'Sem descrição.'}</p>{canManage&&<div className="exerciseCardActions"><button className="secondary" onClick={()=>setEditing({...exercise})}><Edit3 size={15}/>Editar</button><button className="secondary" onClick={()=>toggle(exercise)}>{exercise.active?<Archive size={15}/>:<RefreshCw size={15}/>} {exercise.active?'Arquivar':'Reativar'}</button></div>}</div></article>)}</div>}</div>;
}
