import React,{useEffect,useState} from 'react';
import {Bell,CheckCircle2,Edit3,Plus,Power,Trash2,X} from 'lucide-react';
import {useApp} from '../contexts/AppContext';
import {deleteNotice,saveNotice,toggleNotice} from '../lib/community';

function Modal({title,onClose,children}){return <div className="overlay"><div className="modal"><div className="title"><h2>{title}</h2><button className="iconButton" onClick={onClose}><X/></button></div>{children}</div></div>}
export function StudentNoticePopup(){
 const {data,currentUser}=useApp(); const [dismissed,setDismissed]=useState([]);
 const notices=data.notices.filter(n=>n.active&&n.showPopup&&(n.targetAudience==='students'||n.targetAudience==='all'));
 const notice=currentUser.role==='aluno'?notices.find(n=>!dismissed.includes(n.id)):null;
 if(!notice)return null;
 function close(){setDismissed(current=>[...current,notice.id])}
 return <div className="noticePopupOverlay"><div className="noticePopup"><button className="noticePopupClose" onClick={close}><X/></button><div className="noticePopupIcon"><Bell/></div><span className="eyebrow">AVISO ULTIMATE FIT</span><h2>{notice.title}</h2><p>{notice.body}</p><button className="primary" onClick={close}>Fechar</button></div></div>
}
export function StudentNoticeBoard(){const {data}=useApp();const notices=data.notices.filter(n=>n.active&&n.showDashboard&&(n.targetAudience==='students'||n.targetAudience==='all'));if(!notices.length)return null;return <section className="card pad studentNoticeBoard"><div className="panelTitle"><div><span className="eyebrow">AVISOS</span><h2>ULTIMATE FIT</h2></div><Bell/></div>{notices.map(n=><article key={n.id}><b>{n.title}</b><p>{n.body}</p></article>)}</section>}

function NoticeForm({notice,onClose,onSaved}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await saveNotice({id:notice?.id,title:f.get('title'),body:f.get('body'),targetAudience:f.get('targetAudience'),showPopup:f.get('showPopup')==='on',showDashboard:f.get('showDashboard')==='on',activeFrom:f.get('activeFrom')?new Date(f.get('activeFrom')).toISOString():new Date().toISOString(),activeUntil:f.get('activeUntil')?new Date(f.get('activeUntil')).toISOString():null,active:true});await onSaved();onClose()}catch(err){setError(err.message)}finally{setBusy(false)}}return <Modal title={notice?'Editar aviso':'Novo aviso'} onClose={onClose}><form onSubmit={submit} className="formGrid"><label className="wide">Título *<input name="title" defaultValue={notice?.title||''} required placeholder="Ex.: Jantar de Natal ULTIMATE FIT"/></label><label className="wide">Mensagem *<textarea name="body" rows="6" defaultValue={notice?.body||''} required/></label><label>Destinatários<select name="targetAudience" defaultValue={notice?.targetAudience||'students'}><option value="students">Alunos</option><option value="team">Equipa</option><option value="all">Todos</option></select></label><label>Início<input name="activeFrom" type="datetime-local" defaultValue={notice?.activeFrom?notice.activeFrom.slice(0,16):''}/></label><label className="wide">Fim (opcional)<input name="activeUntil" type="datetime-local" defaultValue={notice?.activeUntil?notice.activeUntil.slice(0,16):''}/></label><label className="checkLine"><input name="showPopup" type="checkbox" defaultChecked={notice?.showPopup!==false}/> Mostrar como pop-up ao entrar</label><label className="checkLine"><input name="showDashboard" type="checkbox" defaultChecked={notice?.showDashboard!==false}/> Manter no dashboard</label>{error&&<div className="errorBanner wide">{error}</div>}<div className="modalActions wide"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'A guardar…':'Guardar aviso'}</button></div></form></Modal>}

export function NoticeManager(){const {data,refreshCommunity}=useApp();const [form,setForm]=useState(null),[open,setOpen]=useState(false),[message,setMessage]=useState('');async function run(fn,msg){await fn();setMessage(msg);await refreshCommunity()}return <div className="noticeManager"><div className="backofficeSectionHeader"><div><h2>Avisos e pop-ups</h2><p>Cria comunicações que podem aparecer ao aluno quando entra na app e permanecer no dashboard.</p></div><button className="primary" onClick={()=>{setForm(null);setOpen(true)}}><Plus size={16}/>Novo aviso</button></div>{message&&<div className="successBanner"><CheckCircle2 size={17}/>{message}</div>}<div className="noticeAdminList">{data.notices.map(n=><article className="card pad" key={n.id}><div className="grow"><div className="titleLine"><b>{n.title}</b><span className={n.active?'badge green':'badge gray'}>{n.active?'Ativo':'Inativo'}</span></div><p>{n.body}</p><small>{n.showPopup?'Pop-up · ':''}{n.showDashboard?'Dashboard · ':''}{n.targetAudience==='students'?'Alunos':n.targetAudience==='team'?'Equipa':'Todos'}</small></div><div className="noticeAdminActions"><button className="secondary" onClick={()=>{setForm(n);setOpen(true)}}><Edit3 size={15}/>Editar</button><button className="secondary" onClick={()=>run(()=>toggleNotice(n.id,!n.active),n.active?'Aviso desativado.':'Aviso ativado.')}><Power size={15}/>{n.active?'Desativar':'Ativar'}</button><button className="iconDanger" onClick={()=>window.confirm('Eliminar este aviso?')&&run(()=>deleteNotice(n.id),'Aviso eliminado.')}><Trash2 size={16}/></button></div></article>)}</div>{open&&<NoticeForm notice={form} onClose={()=>setOpen(false)} onSaved={refreshCommunity}/>}</div>}
