import { createClient } from 'npm:@supabase/supabase-js@2.111.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}
const BREVO_ENDPOINT = 'https://api.brevo.com/v3/smtp/email'
const APP_URL = (Deno.env.get('APP_URL') || 'https://app.ultimatefit.pt').replace(/\/$/, '')
const EMAIL_RE = /^[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}$/i

type Recipient = { email:string; name:string; firstName:string; studentId?:string|null; contactId?:string|null; unsubscribeToken?:string }
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json'}})}
function cleanEmail(value:unknown){return String(value??'').trim().toLowerCase()}
function validEmail(value:string){return EMAIL_RE.test(value)}
function safeText(value:unknown,max=5000){return String(value??'').trim().slice(0,max)}
function sanitizeHtml(raw:unknown){let html=String(raw??'').slice(0,250000);html=html.replace(/<(script|style|iframe|object|embed|form|input|textarea|select|button)[\s\S]*?<\/\1\s*>/gi,'');html=html.replace(/<(script|style|iframe|object|embed|form|input|textarea|select|button)\b[^>]*\/?>/gi,'');html=html.replace(/\son[a-z]+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi,'');html=html.replace(/(href|src)\s*=\s*(["'])\s*javascript:[\s\S]*?\2/gi,'$1="#"');return html.trim()}
function stripHtml(html:string){return html.replace(/<br\s*\/?>/gi,'\n').replace(/<\/p>/gi,'\n\n').replace(/<\/li>/gi,'\n').replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\n{3,}/g,'\n\n').trim()}
function personalize(value:string,r:Recipient){return value.replace(/{{\s*nome\s*}}/gi,r.name||r.firstName||'').replace(/{{\s*primeiro_nome\s*}}/gi,r.firstName||r.name?.split(' ')[0]||'')}
function emailHtml(c:any,r:Recipient,unsubscribeHref:string){const content=personalize(sanitizeHtml(c.html_content),r),preheader=personalize(safeText(c.preheader,300),r);return `<!doctype html><html lang="pt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#0a0a0a;color:#f7f7f7;font-family:Arial,Helvetica,sans-serif">${preheader?`<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent">${preheader.replace(/[<>&]/g,'')}</div>`:''}<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#0a0a0a"><tr><td align="center" style="padding:28px 14px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#111;border:1px solid #2a2a2a;border-radius:18px;overflow:hidden"><tr><td style="padding:28px 30px 20px;border-bottom:1px solid #242424"><img src="${APP_URL}/brand/ultimatefit-logo.webp" width="220" alt="ULTIMATE FIT" style="display:block;max-width:70%;height:auto"></td></tr><tr><td style="padding:30px;color:#f7f7f7;font-size:16px;line-height:1.65">${content}</td></tr><tr><td style="padding:22px 30px 28px;border-top:1px solid #242424;color:#9b9ba3;font-size:12px;line-height:1.6"><strong style="color:#ffd908;letter-spacing:.06em">ULTIMATE FIT</strong><br>${c.sender_email}<br><a href="${unsubscribeHref}" style="color:#b8b8b8;text-decoration:underline">Cancelar subscrição</a></td></tr></table></td></tr></table></body></html>`}
function emailText(c:any,r:Recipient){const explicit=safeText(c.text_content,250000),base=explicit||stripHtml(sanitizeHtml(c.html_content));return `${personalize(base,r)}\n\nULTIMATE FIT\n${c.sender_email}`}
async function batched<T>(items:T[],size:number,fn:(item:T)=>Promise<void>){for(let i=0;i<items.length;i+=size)await Promise.all(items.slice(i,i+size).map(fn))}

Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders})
 if(req.method!=='POST')return json({error:'Método não permitido.'},405)
 const supabaseUrl=Deno.env.get('SUPABASE_URL'),serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY'),brevoKey=Deno.env.get('BREVO_API_KEY'),configuredSenderEmail=cleanEmail(Deno.env.get('BREVO_SENDER_EMAIL')),configuredSenderName=safeText(Deno.env.get('BREVO_SENDER_NAME'),120),configuredReplyTo=cleanEmail(Deno.env.get('BREVO_REPLY_TO')||configuredSenderEmail)
 if(!supabaseUrl||!serviceKey)return json({error:'Configuração do servidor incompleta.'},500)
 const token=req.headers.get('Authorization')?.replace(/^Bearer\s+/i,'');if(!token)return json({error:'Sessão em falta.'},401)
 const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}})
 const {data:userData,error:userError}=await admin.auth.getUser(token);if(userError||!userData.user)return json({error:'Sessão inválida.'},401)
 const {data:caller}=await admin.from('profiles').select('id,email,full_name,role,is_active,deleted_at').eq('id',userData.user.id).maybeSingle();if(!caller||!caller.is_active||caller.deleted_at||!['owner','admin'].includes(caller.role))return json({error:'Não tens permissão para enviar campanhas.'},403)
 let body:any;try{body=await req.json()}catch{return json({error:'Pedido inválido.'},400)}
 const action=String(body?.action||'send'),campaignId=safeText(body?.campaignId,64);if(!campaignId)return json({error:'Campanha em falta.'},400)
 const {data:campaign,error:campaignError}=await admin.from('email_campaigns').select('*').eq('id',campaignId).maybeSingle();if(campaignError||!campaign)return json({error:'Campanha não encontrada.'},404)
 if(!campaign.subject?.trim())return json({error:'Indica o assunto do email.'},400);if(!sanitizeHtml(campaign.html_content))return json({error:'O conteúdo do email está vazio.'},400)
 const senderEmail=configuredSenderEmail||cleanEmail(campaign.sender_email),senderName=configuredSenderName||safeText(campaign.sender_name,120),replyTo=configuredReplyTo||cleanEmail(campaign.reply_to);if(!brevoKey||!validEmail(senderEmail)||!senderName)return json({error:'O envio de email ainda não está configurado no servidor.'},503)
 async function sendBrevo(r:Recipient,unsubscribeHref:string){const response=await fetch(BREVO_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','api-key':brevoKey},body:JSON.stringify({sender:{name:senderName,email:senderEmail},replyTo:validEmail(replyTo)?{email:replyTo}:undefined,to:[{email:r.email,name:r.name||undefined}],subject:personalize(campaign.subject,r),htmlContent:emailHtml({...campaign,sender_email:senderEmail},r,unsubscribeHref),textContent:emailText({...campaign,sender_email:senderEmail},r)})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(response.status===401||response.status===403?'O serviço de email recusou a autenticação.':'O serviço de email não conseguiu aceitar esta mensagem.');return String(payload?.messageId||'')}
 if(action==='test'){const testEmail=cleanEmail(body?.testEmail||caller.email);if(!validEmail(testEmail))return json({error:'Indica um email de teste válido.'},400);const r:Recipient={email:testEmail,name:caller.full_name||'Ultimate Fit',firstName:String(caller.full_name||'').split(' ')[0]};try{await sendBrevo(r,APP_URL);return json({ok:true,message:`Email de teste enviado para ${testEmail}.`})}catch(error){return json({error:error instanceof Error?error.message:'Não foi possível enviar o email de teste.'},502)}}
 if(!['draft','failed'].includes(campaign.status))return json({error:campaign.status==='sent'?'Esta campanha já foi enviada.':'Esta campanha já está em processamento.'},409)
 const {data:locked}=await admin.from('email_campaigns').update({status:'sending',last_error:null,updated_at:new Date().toISOString()}).eq('id',campaignId).in('status',['draft','failed']).select('id').maybeSingle();if(!locked)return json({error:'A campanha já está a ser processada.'},409)
 try{
  const recipients:Recipient[]=[]
  if(campaign.audience_type==='imported_contacts'){let q=admin.from('email_contacts').select('id,email,name');if(campaign.audience_ids?.length)q=q.in('id',campaign.audience_ids);const {data,error}=await q;if(error)throw error;for(const item of data||[]){const email=cleanEmail(item.email);if(validEmail(email))recipients.push({email,name:item.name||'',firstName:String(item.name||'').split(' ')[0],contactId:item.id})}}
  else{let q=admin.from('student_profiles').select('id,status,deleted_at,profile:profiles!student_profiles_profile_id_fkey(id,email,full_name,first_name,is_active,deleted_at)');if(campaign.audience_type==='selected_students')q=q.in('id',campaign.audience_ids||[]);if(campaign.audience_type==='active_students')q=q.eq('status','active');q=q.is('deleted_at',null);const {data,error}=await q;if(error)throw error;for(const item of data||[]){const p:any=item.profile;if(!p||p.deleted_at)continue;if(campaign.audience_type==='active_students'&&!p.is_active)continue;const email=cleanEmail(p.email);if(validEmail(email))recipients.push({email,name:p.full_name||'',firstName:p.first_name||String(p.full_name||'').split(' ')[0],studentId:item.id})}}
  const unique=[...new Map(recipients.map(item=>[item.email,item])).values()];if(!unique.length)throw new Error('A campanha não tem destinatários válidos.')
  const emails=unique.map(i=>i.email),prefMap=new Map<string,any>();for(let i=0;i<emails.length;i+=200){const {data}=await admin.from('email_marketing_preferences').select('email,enabled,unsubscribe_token').in('email',emails.slice(i,i+200));for(const pref of data||[])prefMap.set(pref.email,pref)}
  const missing=unique.filter(i=>!prefMap.has(i.email)).map(i=>({email:i.email,enabled:true,source:i.contactId?'imported':'student',updated_by:caller.id}));if(missing.length){const {error}=await admin.from('email_marketing_preferences').upsert(missing,{onConflict:'email',ignoreDuplicates:true});if(error)throw error;const {data}=await admin.from('email_marketing_preferences').select('email,enabled,unsubscribe_token').in('email',missing.map(m=>m.email));for(const pref of data||[])prefMap.set(pref.email,pref)}
  const eligible=unique.filter(i=>prefMap.get(i.email)?.enabled!==false).map(i=>({...i,unsubscribeToken:prefMap.get(i.email)?.unsubscribe_token}));if(!eligible.length)throw new Error('Nenhum dos contactos selecionados aceita comunicações por email.')
  await admin.from('email_campaign_recipients').upsert(eligible.map(i=>({campaign_id:campaignId,student_id:i.studentId||null,contact_id:i.contactId||null,email:i.email,recipient_name:i.name||null,status:'pending'})),{onConflict:'campaign_id,email',ignoreDuplicates:true})
  const {data:existingRows}=await admin.from('email_campaign_recipients').select('id,email,status').eq('campaign_id',campaignId),existingByEmail=new Map((existingRows||[]).map((r:any)=>[r.email,r])),sentStatuses=new Set(['sent','delivered','opened','clicked']),toSend=eligible.filter(i=>!sentStatuses.has(existingByEmail.get(i.email)?.status))
  await batched(toSend,5,async r=>{const row:any=existingByEmail.get(r.email),unsubscribeHref=`${supabaseUrl}/functions/v1/unsubscribe-email?token=${encodeURIComponent(r.unsubscribeToken||'')}`;try{const messageId=await sendBrevo(r,unsubscribeHref);await admin.from('email_campaign_recipients').update({status:'sent',provider_message_id:messageId||null,sent_at:new Date().toISOString(),error:null,updated_at:new Date().toISOString()}).eq('id',row.id)}catch(error){await admin.from('email_campaign_recipients').update({status:'failed',error:error instanceof Error?error.message.slice(0,500):'Falha de envio',updated_at:new Date().toISOString()}).eq('id',row.id)}})
  const {data:finalRows}=await admin.from('email_campaign_recipients').select('status').eq('campaign_id',campaignId),statuses=finalRows||[],sentCount=statuses.filter((r:any)=>sentStatuses.has(r.status)).length,failedCount=statuses.filter((r:any)=>r.status==='failed').length,status=failedCount>0?'failed':'sent',lastError=failedCount?`Não foi possível enviar ${failedCount} dos ${eligible.length} emails.`:null
  await admin.from('email_campaigns').update({status,recipients_count:eligible.length,sent_count:sentCount,failed_count:failedCount,sent_at:sentCount>0?new Date().toISOString():null,last_error:lastError,updated_at:new Date().toISOString()}).eq('id',campaignId)
  await admin.from('audit_logs').insert({actor_id:caller.id,action:'email_campaign_sent',entity_type:'email_campaign',entity_id:campaignId,metadata:{recipients_count:eligible.length,sent_count:sentCount,failed_count:failedCount}})
  if(failedCount)return json({ok:false,partial:sentCount>0,message:lastError,sentCount,failedCount,recipientsCount:eligible.length},207)
  return json({ok:true,message:`Campanha enviada para ${sentCount} destinatários.`,sentCount,failedCount:0,recipientsCount:eligible.length})
 }catch(error){const message=error instanceof Error?error.message:'Não foi possível enviar a campanha.';await admin.from('email_campaigns').update({status:'failed',last_error:message.slice(0,1000),updated_at:new Date().toISOString()}).eq('id',campaignId);return json({error:message},400)}
})
