import React,{useMemo,useState} from 'react';
import {AppProvider,useApp} from './contexts/AppContext';
import {AuthProvider,useAuth} from './contexts/AuthContext';
import LoginScreen from './components/LoginScreen';
import {Activity,Apple,BarChart3,BookOpen,ClipboardList,Dumbbell,FileText,Flag,Home,LogOut,MessageSquare,Plus,Search,Settings,Target,User,UserCog,Users,X} from 'lucide-react';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';

const adminNav=[['dashboard','Dashboard',Home],['students','Alunos',Users],['trainers','Professores',UserCog],['assessments','Avaliações',ClipboardList],['evolution','Evolução',BarChart3],['plans','Planos de treino',Dumbbell],['nutrition','Nutrição',Apple],['goals','Objetivos',Target],['challenges','Desafios',Flag],['exercises','Biblioteca',BookOpen],['messages','Avisos',MessageSquare],['reports','Relatórios PDF',FileText],['settings','Backoffice',Settings]];
const trainerNav=adminNav.filter(x=>!['trainers','settings'].includes(x[0]));
const studentNav=[['dashboard','Início',Home],['plans','Treino',Dumbbell],['nutrition','Nutrição',Apple],['assessments','Avaliações',ClipboardList],['evolution','Evolução',BarChart3],['goals','Objetivos',Target],['challenges','Desafios',Flag],['messages','Avisos',MessageSquare],['reports','Relatórios',FileText],['profile','Perfil',User]];

const cx=(...a)=>a.filter(Boolean).join(' ');
function Card({children,className=''}){return <div className={cx('card',className)}>{children}</div>}
function Badge({children,tone='gray'}){return <span className={`badge ${tone}`}>{children}</span>}
function Logo(){return <div className="logo"><div className="logoMark">UF</div><div>ULTIMATE <span>FIT</span></div></div>}

function Shell(){
 const {currentUser}=useApp();
 const {signOut}=useAuth();
 const [page,setPage]=useState('dashboard');
 const nav=currentUser.role==='admin'?adminNav:currentUser.role==='professor'?trainerNav:studentNav;
 return <div className="appShell">
  <aside className="sidebar"><Logo/><div className="navList">{nav.map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>setPage(key)}><Icon size={18}/>{label}</button>)}</div></aside>
  <main className="main"><header className="topbar"><div className="mobileLogo"><Logo/></div><div className="env">Supabase ligado · ambiente de desenvolvimento</div><div className="userTools"><div className="userIdentity"><b>{currentUser.name}</b><small>{currentUser.role}</small></div><div className="avatar">{currentUser.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><button className="logoutButton" onClick={signOut} title="Terminar sessão"><LogOut size={18}/></button></div></header>
  <div className="content"><PageRouter page={page}/></div>
  <nav className="bottomNav">{nav.slice(0,5).map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>setPage(key)}><Icon size={20}/><small>{label}</small></button>)}</nav>
  </main>
 </div>
}

function PageRouter({page}){
 const map={dashboard:<Dashboard/>,students:<Students/>,trainers:<Trainers/>,assessments:<Assessments/>,evolution:<Evolution/>,plans:<Plans/>,nutrition:<Nutrition/>,goals:<Goals/>,challenges:<Challenges/>,exercises:<Exercises/>,messages:<Messages/>,reports:<Reports/>,settings:<SettingsPage/>,profile:<Profile/>};
 return map[page]||<Dashboard/>;
}
function Heading({title,sub,action}){return <div className="heading"><div><h1>{title}</h1>{sub&&<p>{sub}</p>}</div>{action}</div>}
function Kpi({icon:Icon,label,value}){return <Card className="kpi"><div className="iconBox"><Icon/></div><div><small>{label}</small><strong>{value}</strong></div></Card>}

function Dashboard(){
 const {data,currentUser}=useApp();
 const student=data.students.find(s=>s.userId===currentUser.id)||data.students[0];
 if(currentUser.role==='aluno') return <StudentDashboard student={student}/>;
 const visibleStudents=currentUser.role==='admin'?data.students:data.students.filter(s=>s.trainerIds?.includes(currentUser.id));
 return <><Heading title={`Olá, ${currentUser.name.split(' ')[0]}`} sub="Visão geral da plataforma ULTIMATE FIT."/>
 <div className="grid four"><Kpi icon={Users} label="Alunos ativos" value={visibleStudents.filter(s=>s.active).length}/><Kpi icon={Dumbbell} label="Planos ativos" value={data.plans.filter(p=>p.status==='Ativo').length}/><Kpi icon={ClipboardList} label="Avaliações" value={data.assessments.length}/><Kpi icon={BookOpen} label="Exercícios" value={data.exercises.length}/></div>
 <div className="grid two section"><Card className="pad"><h2>Alunos recentes</h2>{visibleStudents.map(s=><div className="listRow" key={s.id}><div className="avatar small">{s.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="grow"><b>{s.name}</b><small>{s.objective}</small></div><Badge tone="green">Ativo</Badge></div>)}</Card><Card className="pad"><h2>Avisos e trabalho pendente</h2><div className="notice">2 planos devem ser revistos nas próximas semanas.</div><div className="notice">1 avaliação física aguarda relatório.</div><div className="notice">Modo Coming Soon encontra-se ativo.</div></Card></div></>;
}
function StudentDashboard({student}){const {data}=useApp();const plan=data.plans.find(p=>p.studentId===student.id);return <><Heading title={`Olá, ${student.name.split(' ')[0]} 👋`} sub="A tua área pessoal ULTIMATE FIT."/><Card className="heroCard"><div><small>PLANO ATIVO</small><h2>{plan?.title||'Sem plano ativo'}</h2><p>{student.objective}</p></div><Dumbbell size={46}/></Card><div className="grid four"><Kpi icon={Dumbbell} label="Treinos" value={plan?.sessions.length||0}/><Kpi icon={Activity} label="Avaliações" value={data.assessments.filter(a=>a.studentId===student.id).length}/><Kpi icon={Target} label="Objetivos" value={data.goals.filter(g=>g.studentId===student.id).length}/><Kpi icon={MessageSquare} label="Avisos" value={data.messages.filter(m=>m.studentId===student.id).length}/></div><Evolution compact studentId={student.id}/></>}

function Students(){
 const {data,update,currentUser}=useApp();const [q,setQ]=useState('');const [open,setOpen]=useState(false);
 const list=(currentUser.role==='admin'?data.students:data.students.filter(s=>s.trainerIds?.includes(currentUser.id))).filter(s=>s.name.toLowerCase().includes(q.toLowerCase()));
 function add(e){e.preventDefault();const f=new FormData(e.currentTarget);const student={id:`s-${Date.now()}`,name:f.get('name'),nif:f.get('nif'),birth:f.get('birth'),sex:f.get('sex'),phone:f.get('phone'),email:f.get('email'),objective:f.get('objective'),trainerIds:[f.get('trainer')],active:true,photo:''};update('students',x=>[...x,student]);setOpen(false)}
 return <><Heading title="Alunos" sub="Registo, dados pessoais, professor responsável e histórico." action={<button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/>Novo aluno</button>}/><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar aluno..."/></div><div className="grid three">{list.map(s=><Card className="pad studentCard" key={s.id}><div className="listRow"><div className="avatar">{s.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="grow"><h3>{s.name}</h3><small>{s.email}</small></div><Badge tone="green">Ativo</Badge></div><div className="infoGrid"><Info l="NIF" v={s.nif}/><Info l="Telemóvel" v={s.phone}/><Info l="Nascimento" v={s.birth}/><Info l="Objetivo" v={s.objective}/></div></Card>)}</div>{open&&<Modal title="Novo aluno" close={()=>setOpen(false)}><form onSubmit={add} className="formGrid"><Input name="name" label="Nome" required/><Input name="nif" label="NIF"/><Input name="birth" label="Data de nascimento" type="date"/><Select name="sex" label="Sexo" options={['Feminino','Masculino','Outro']}/><Input name="phone" label="Telemóvel"/><Input name="email" label="Email" type="email" required/><Select name="trainer" label="Professor" options={data.users.filter(u=>['admin','professor'].includes(u.role)).map(u=>({value:u.id,label:u.name}))}/><Input name="objective" label="Objetivo"/><button className="primary full">Guardar aluno</button></form></Modal>}</>;
}
function Trainers(){const {data,update}=useApp();const [open,setOpen]=useState(false);function add(e){e.preventDefault();const f=new FormData(e.currentTarget);update('users',x=>[...x,{id:`u-${Date.now()}`,role:'professor',name:f.get('name'),email:f.get('email'),active:true}]);setOpen(false)}function toggle(id){update('users',x=>x.map(u=>u.id===id?{...u,active:!u.active}:u))}return <><Heading title="Professores" sub="Contas, permissões e estado dos profissionais." action={<button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/>Adicionar professor</button>}/><div className="grid three">{data.users.filter(u=>['admin','professor'].includes(u.role)).map(u=><Card className="pad" key={u.id}><div className="listRow"><div className="avatar">{u.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="grow"><h3>{u.name}</h3><small>{u.email}</small></div><Badge tone={u.role==='admin'?'yellow':'gray'}>{u.role}</Badge></div><button className="secondary full" onClick={()=>toggle(u.id)}>{u.active?'Desativar conta':'Reativar conta'}</button></Card>)}</div>{open&&<Modal title="Adicionar professor" close={()=>setOpen(false)}><form onSubmit={add} className="formGrid"><Input name="name" label="Nome" required/><Input name="email" label="Email" type="email" required/><button className="primary full">Criar conta e preparar convite</button></form></Modal>}</>}

function Assessments(){const {data,update,currentUser}=useApp();const [studentId,setStudentId]=useState(data.students[0]?.id);const students=currentUser.role==='admin'?data.students:data.students.filter(s=>s.trainerIds?.includes(currentUser.id));function add(e){e.preventDefault();const f=new FormData(e.currentTarget);const n=k=>Number(f.get(k)||0);update('assessments',x=>[...x,{id:`a-${Date.now()}`,studentId,date:f.get('date'),weight:n('weight'),height:n('height'),fat:n('fat'),muscle:n('muscle'),visceral:n('visceral'),waist:n('waist'),abdomen:n('abdomen'),hip:n('hip'),armR:n('armR'),armL:n('armL'),thighR:n('thighR'),thighL:n('thighL'),notes:f.get('notes')}]);e.currentTarget.reset()}return <><Heading title="Avaliações físicas" sub="Bioimpedância, antropometria, anamnese e fotografia."/><div className="grid two"><Card className="pad"><h2>Nova avaliação</h2><form onSubmit={add} className="formGrid"><Select name="student" label="Aluno" value={studentId} onChange={e=>setStudentId(e.target.value)} options={students.map(s=>({value:s.id,label:s.name}))}/><Input name="date" label="Data" type="date" required/><Input name="weight" label="Peso (kg)" type="number" step="0.1"/><Input name="height" label="Altura (m)" type="number" step="0.01"/><Input name="fat" label="Massa gorda (%)" type="number" step="0.1"/><Input name="muscle" label="Massa muscular (kg)" type="number" step="0.1"/><Input name="visceral" label="Gordura visceral" type="number"/><Input name="waist" label="Cintura (cm)" type="number" step="0.1"/><Input name="abdomen" label="Abdómen (cm)" type="number" step="0.1"/><Input name="hip" label="Anca (cm)" type="number" step="0.1"/><Input name="armR" label="Braço direito" type="number" step="0.1"/><Input name="armL" label="Braço esquerdo" type="number" step="0.1"/><Input name="thighR" label="Coxa direita" type="number" step="0.1"/><Input name="thighL" label="Coxa esquerda" type="number" step="0.1"/><label className="wide">Breve anamnese<textarea name="notes"/></label><div className="upload wide">Fotografias privadas: frente · perfil · costas<br/><small>Upload real será ligado ao armazenamento privado.</small></div><button className="primary full">Guardar avaliação</button></form></Card><Card className="pad"><h2>Histórico</h2>{data.assessments.filter(a=>a.studentId===studentId).sort((a,b)=>b.date.localeCompare(a.date)).map(a=><div className="assessment" key={a.id}><div><b>{a.date}</b><small>{a.notes}</small></div><div><strong>{a.weight} kg</strong><span>{a.fat}% MG</span></div></div>)}</Card></div></>}

function Evolution({compact=false,studentId}){const {data,currentUser}=useApp();const sid=studentId||data.students.find(s=>s.userId===currentUser.id)?.id||data.students[0]?.id;const rows=data.assessments.filter(a=>a.studentId===sid).sort((a,b)=>a.date.localeCompare(b.date));const first=rows[0],last=rows.at(-1);const metrics=[['Peso','weight','kg'],['Massa gorda','fat','%'],['Massa muscular','muscle','kg'],['Cintura','waist','cm']];return <div className={compact?'section':''}>{!compact&&<Heading title="Evolução" sub="Comparação automática entre avaliações."/>}<div className="grid four">{metrics.map(([label,key,unit])=><Card className="metric" key={key}><small>{label}</small><strong>{last?.[key]??'—'} {unit}</strong><span>{first&&last?`${(last[key]-first[key]).toFixed(1)} ${unit} desde o início`:'Sem comparação'}</span></Card>)}</div><Card className="pad section"><h2>Evolução corporal</h2><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="date" tick={{fill:'#888'}}/><YAxis tick={{fill:'#888'}}/><Tooltip contentStyle={{background:'#111',border:'1px solid #333'}}/><Line dataKey="weight" stroke="#ffd908" strokeWidth={3}/><Line dataKey="waist" stroke="#aaa" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Card>{!compact&&<Card className="pad section"><h2>Comparação fotográfica</h2><div className="grid two"><div className="photoBox">Avaliação inicial</div><div className="photoBox">Avaliação atual</div></div></Card>}</div>}

function Plans(){const {data,currentUser}=useApp();const student=data.students.find(s=>s.userId===currentUser.id);const plans=currentUser.role==='aluno'?data.plans.filter(p=>p.studentId===student?.id):data.plans;return <><Heading title="Planos de treino" sub="Prescrição estruturada com exercícios, séries, repetições e notas." action={currentUser.role!=='aluno'?<button className="primary"><Plus size={17}/>Novo plano</button>:null}/>{plans.map(p=><Card className="pad section" key={p.id}><div className="titleLine"><div><Badge tone="green">{p.status}</Badge><h2>{p.title}</h2><small>{p.weeks} semanas</small></div><Dumbbell size={38}/></div>{p.sessions.map(s=><div className="session" key={s.name}><h3>{s.name}</h3>{s.items.map((it,i)=>{const ex=data.exercises.find(e=>e.id===it.exerciseId);return <div className="exerciseRow" key={i}><div className="media">GIF</div><div className="grow"><b>{ex?.name}</b><small>{ex?.group} · {ex?.equipment}</small><p>{it.sets} séries · {it.reps} repetições · {it.rest}</p></div></div>})}</div>)}</Card>)}</>}
function Nutrition(){const {data,currentUser}=useApp();const student=data.students.find(s=>s.userId===currentUser.id);const items=currentUser.role==='aluno'?data.nutrition.filter(n=>n.studentId===student?.id):data.nutrition;return <><Heading title="Nutrição" sub="Planos alimentares e documentos associados." action={currentUser.role!=='aluno'?<button className="primary"><Plus size={17}/>Adicionar PDF</button>:null}/><div className="grid three section">{items.map(n=><Card className="pad" key={n.id}><Apple className="yellow" size={34}/><h2>{n.title}</h2><p>{n.notes}</p><button className="secondary full">Abrir {n.fileName}</button></Card>)}</div></>}
function Goals(){const {data,currentUser}=useApp();const student=data.students.find(s=>s.userId===currentUser.id);const items=currentUser.role==='aluno'?data.goals.filter(g=>g.studentId===student?.id):data.goals;return <><Heading title="Objetivos" sub="Metas mensuráveis e acompanhamento do progresso."/><div className="grid three section">{items.map(g=><Card className="pad" key={g.id}><Target className="yellow"/><h2>{g.title}</h2><p>Meta: <b>{g.target}</b></p><div className="progress"><span style={{width:`${g.progress}%`}}/></div><small>{g.progress}% concluído · até {g.deadline}</small></Card>)}</div></>}
function Challenges(){const {data}=useApp();return <><Heading title="Desafios" sub="Compromisso, consistência e integração futura com desafios.ultimatefit.pt."/><div className="grid three section">{data.challenges.map(c=><Card className="pad" key={c.id}><Flag className="yellow"/><h2>{c.title}</h2><p>{c.description}</p><Badge tone="green">Ativo</Badge></Card>)}</div></>}
function Exercises(){const {data}=useApp();const [q,setQ]=useState('');const [group,setGroup]=useState('Todos');const groups=['Todos',...new Set(data.exercises.map(e=>e.group))];const list=data.exercises.filter(e=>(group==='Todos'||e.group===group)&&e.name.toLowerCase().includes(q.toLowerCase()));return <><Heading title="Biblioteca de exercícios" sub={`${data.exercises.length} exercícios iniciais, preparados para GIFs/vídeos próprios.`}/><div className="filters"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar exercício..."/></div><select value={group} onChange={e=>setGroup(e.target.value)}>{groups.map(g=><option key={g}>{g}</option>)}</select></div><div className="grid three">{list.map(e=><Card className="exerciseCard" key={e.id}><div className="exerciseMedia">GIF / VÍDEO</div><div className="pad"><Badge tone="yellow">{e.group}</Badge><h3>{e.name}</h3><small>{e.equipment} · {e.type} · {e.level}</small><p>{e.description}</p></div></Card>)}</div></>}
function Messages(){const {data,currentUser}=useApp();const student=data.students.find(s=>s.userId===currentUser.id);const items=currentUser.role==='aluno'?data.messages.filter(m=>m.studentId===student?.id):data.messages;return <><Heading title="Avisos" sub="Comunicação assíncrona entre professor e aluno."/><div className="section">{items.map(m=><Card className="pad message" key={m.id}><MessageSquare className="yellow"/><div><h3>{m.title}</h3><p>{m.body}</p><small>{m.date}</small></div></Card>)}</div></>}
function Reports(){const {data}=useApp();return <><Heading title="Relatórios PDF" sub="Geração automática a partir das avaliações físicas."/><Card className="pad section"><h2>Relatório de avaliação</h2><p>Seleciona um aluno e duas avaliações para criar um documento com dados, diferenças, gráficos, observações e identidade ULTIMATE FIT.</p><div className="formGrid"><Select label="Aluno" options={data.students.map(s=>s.name)}/><Select label="Avaliação inicial" options={data.assessments.map(a=>a.date)}/><Select label="Avaliação atual" options={data.assessments.map(a=>a.date)}/><button className="primary full"><FileText size={17}/>Gerar relatório demonstrativo</button></div></Card></>}
function SettingsPage(){const {data,setData}=useApp();const s=data.settings;return <><Heading title="Backoffice" sub="Definições globais e controlo da aplicação."/><div className="grid two section"><Card className="pad"><h2>Modo público</h2><div className="setting"><div><b>Página Coming Soon</b><small>Enquanto ativa, o público vê apenas a página de lançamento.</small></div><button className={s.comingSoon?'toggle on':'toggle'} onClick={()=>setData(d=>({...d,settings:{...d.settings,comingSoon:!d.settings.comingSoon}}))}><span/></button></div></Card><Card className="pad"><h2>Permissões previstas</h2><p><b>Admin:</b> acesso total.</p><p><b>Professor:</b> apenas alunos atribuídos.</p><p><b>Aluno:</b> apenas os próprios dados.</p></Card><Card className="pad"><h2>Convites</h2><p>Fluxo final: criação no backoffice → email para definir password → instruções complementares por WhatsApp.</p></Card><Card className="pad"><h2>PWA</h2><p>Manifesto instalável já incluído. Ícone e experiência mobile serão validados antes do deploy.</p></Card></div></>}
function Profile(){const {currentUser}=useApp();return <><Heading title="Perfil" sub="Dados da conta e preferências pessoais."/><Card className="pad section"><div className="listRow"><div className="avatar big">{currentUser.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h2>{currentUser.name}</h2><p>{currentUser.email}</p><Badge tone="yellow">{currentUser.role}</Badge></div></div></Card></>}

function Modal({title,close,children}){return <div className="overlay"><div className="modal"><div className="title"><h2>{title}</h2><button className="iconButton" onClick={close}><X/></button></div>{children}</div></div>}
function Input({label,...props}){return <label>{label}<input {...props}/></label>}
function Select({label,options=[],...props}){return <label>{label}<select {...props}>{options.map((o,i)=>typeof o==='string'?<option key={i}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function Info({l,v}){return <div className="info"><small>{l}</small><b>{v||'—'}</b></div>}

function AppGate(){
 const {configured,loading,session,profile}=useAuth();
 if(!configured) return <div className="appState"><Logo/><h1>Configuração em falta</h1><p>As variáveis VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY ainda não estão disponíveis neste deployment.</p></div>;
 if(loading) return <div className="appState"><Logo/><div className="loader"/><p>A preparar a aplicação…</p></div>;
 if(!session) return <LoginScreen/>;
 if(!profile) return <div className="appState"><Logo/><h1>Perfil indisponível</h1><p>Não foi possível carregar o perfil associado a esta conta.</p></div>;
 if(!profile.is_active) return <div className="appState"><Logo/><h1>Conta desativada</h1><p>Contacta a administração do ULTIMATE FIT.</p></div>;
 return <AppProvider><Shell/></AppProvider>;
}

export default function App(){return <AuthProvider><AppGate/></AuthProvider>}
